### ISSUE TITLE
Can you add an option to edit the frames of the page layout as 2d vectors, like the openpose puppet?

### ISSUE THREAD

**Issue by Emasoft** [new-sankaku/stable-diffusion-webui-simple-manga-maker#10]
Great addon! Can you add an option to edit the frames of the page layout as 2d vectors, like the openpose puppet? Adding and removing columns in each row independently can be done with sliders, we just need to move the nodes at the corners.

**Comment by new-sankaku** [comment]
You can scale and move the frame. After selecting a frame, drop the image and UNDO to gain control over the frame. It's an unintentional bug though.

Adding and deleting frames is also possible by adding implementation.

However, adding a node to a frame and moving it arbitrarily requires some effort.

Please wait patiently. I think it will be released in stages.

**Comment by new-sankaku** [comment]
Now supports moving, changing scale, and deleting manga panels. Added the ability to add new panels (attached image). The newly added panel allows you to move not only the scale but also the vertices of the rectangle.

![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/133557155/3611a5a1-9be1-4bfe-895b-0356221e02d4)
