### ISSUE TITLE
High resolution upscale not working.

### ISSUE THREAD

**Issue by 0m3ga4** [new-sankaku/stable-diffusion-webui-simple-manga-maker#15]
**### ORIGINAL:**
I can't seem to do anything that will make this work.
![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/102787026/f296a751-e040-4721-8c3f-4094c162756d)

For some reason it is a text box where you can type instead of a selection list like the model and sampling method.
It doesn't matter what I type into the box, it doesn't do a high resolution upscale. I'm not sure how to enable it.
I've tried typing the exact names of the upscalers I use in a regular Txt2Img generation, but nothing happens.

I would appreciate any help, and if the feature is simply not working at the moment I recommend a toggle checkbox for enabling or disabling it.

(As a side-note, it would be extremely useful to have a button in various places that allows you to repeat a previous render using the same seed, when paired with a high-resolution upscale toggle this allows you to test the prompt at low resolution before committing to the longer render times of an upscale).

### **CHAT GPT TRANSLATION:**
何をやってもこれがうまくいきません。
![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/102787026/f296a751-e040-4721-8c3f-4094c162756d)

何故かモデルやサンプリングメソッドの選択リストではなく、入力できるテキストボックスになっています。
ボックスに何を入力しても、高解像度のアップスケールはできません。どうやって有効にするのかわかりません。
通常のTxt2Img生成で使用するアップスケーラーの正確な名前を入力してみましたが、何も起こりません。

どんな助けでもありがたいですし、この機能が現在動作していないだけなら、有効化または無効化するためのトグルチェックボックスをお勧めします。

（ちなみに、高解像度アップスケールのトグルと組み合わせて、同じシードを使用して以前のレンダーを繰り返すボタンがあれば非常に便利です。これにより、アップスケールの長いレンダー時間にコミットする前に低解像度でプロンプトをテストすることができます）。

### **DEEPL TRANSLATION:**
どうにもうまくいかないのです。
![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/102787026/f296a751-e040-4721-8c3f-4094c162756d)

なぜか、モデルやサンプリング方法のような選択リストではなく、入力できるテキストボックスになっています。
何を入力しても、高解像度のアップスケールは行われません。有効化する方法がわかりません。
通常のTxt2Img生成で使用するアップスケーラーの名前を正確に入力してみましたが、何も起こりません。

もし、この機能が単に現在機能していないのであれば、有効・無効のトグルチェックボックスをお勧めします。

(余談ですが、同じシードを使用して以前のレンダリングを繰り返すことができるボタンが様々な場所にあると非常に便利です。高解像度アップスケールトグルと組み合わせると、アップスケールの長いレンダリング時間にコミットする前に、低解像度でプロンプトをテストすることができます)。

**Comment by new-sankaku** [comment]
thank you for contacting!
I understand the problem. I'll fix it!
I think this will be fixed soon.

>(As a side-note, it would be extremely useful to have a button in various places that allows you to repeat a previous render using the same seed, when paired with a high-resolution upscale toggle this allows you to test the prompt at low resolution before committing to the longer render times of an upscale).

The area for layers is narrow, isn't it? Let's consider a feature like PromptHold!

**Comment by 0m3ga4** [comment]
> thank you for contacting! I understand the problem. I'll fix it! I think this will be fixed soon.
> 
> > (As a side-note, it would be extremely useful to have a button in various places that allows you to repeat a previous render using the same seed, when paired with a high-resolution upscale toggle this allows you to test the prompt at low resolution before committing to the longer render times of an upscale).
> 
> The area for layers is narrow, isn't it? Let's consider a feature like PromptHold!



Thank you! I forgot to mention it would be important and helpful to have these settings available for the high-resoultion upscale:
![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/102787026/46ca2434-92a8-4313-bafb-a9b10019b771)

**Comment by 0m3ga4** [comment]
I believe I'm updated to the latest version and I don't see any difference. High Resolution Upscale still doesn't occur.

![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/102787026/55716b89-9c9e-4170-bafd-2bdd6e547bee)
![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/102787026/3dbed0d7-afd7-4dc8-a5c6-71aaf3cf3248)

**Comment by 0m3ga4** [comment]
Awesome work, thank you very much!
