### ISSUE TITLE
Arrow keys move image instead of navigating T2I text panel.

### ISSUE THREAD

**Issue by 0m3ga4** [new-sankaku/stable-diffusion-webui-simple-manga-maker#17]
When trying to navigate the text cursor in the T2I window with the arrow keys, it instead moves the currently selected image or panel.
![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/102787026/6783db22-23d5-4287-b0ed-674d67d28dbc)

**Comment by new-sankaku** [comment]
Thank you very much!
This issue has been fixed.
