### ISSUE TITLE
Community Discord?

### ISSUE THREAD

**Issue by 0m3ga4** [new-sankaku/stable-diffusion-webui-simple-manga-maker#20]
Would love to see a community Discord server for this plugin.

People could share their work in progress comics, share tips and tricks, as well as get real-time communication with you and other helpful community members for troubleshooting issues when applicable.

**Comment by new-sankaku** [comment]
Come to think of it, I see a software community using Discord. Will people gather?

**Comment by 0m3ga4** [comment]
Yes I believe this is the type of thing that would attract a tight-knit community. I would be the first to join!

As an added bonus when using Discord, there are bots that can automatically translate messages to display in English and Japanese simultaneously so that everybody can communicate. I'm sure you could figure that out, but if not I would be glad to assist in setting it up.
