### ISSUE TITLE
Larger Workspace for Panels

### ISSUE THREAD

**Issue by LindezaBlue** [new-sankaku/stable-diffusion-webui-simple-manga-maker#27]
### Improved Preview Window

Everything so far has been a really joy to use and every easy to configure. One thing I think could use some improvement is the preview window for the panels. Even with a wide-screen monitor it's pretty small to see details and I have to force zoom the browser to get a better view.

**Example:**
![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/141217866/e2f0ed97-1027-4696-8ca4-f534d902a641)

Maybe a _slightly_ larger Preview Window, or the option to select different sized preview windows for those that have different screen sizes would be a wonderful addition. 

Thank you again for making such a wonderful tool!~

Extra info if needed:
- DiffusionUI: Forge/A1111
- Operating System: Windows 11
- GPU: RTX 2060 6GB

**Comment by 3blackbar** [comment]
yes i agree, move all buttons to the sides, no buttons under comic page and above it to not waste space

**Comment by LindezaBlue** [comment]
> There is definitely dead space. It's especially noticeable when editing vertically long images. Let's go ahead and move the buttons below the image editing area. Let's try moving them a bit.
> 
> ![image](https://private-user-images.githubusercontent.com/133557155/335192338-c5da9743-e121-4ef4-a0d6-e60d57563e27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxODcwOTMsIm5iZiI6MTcxNzE4Njc5MywicGF0aCI6Ii8xMzM1NTcxNTUvMzM1MTkyMzM4LWM1ZGE5NzQzLWUxMjEtNGVmNC1hMGQ2LWU2MGQ1NzU2M2UyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQyMDE5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGRiYzg1ODEzYTg1Y2U4NzNmNTVmZTQ2NGY2NTUxNTNlMjZmYTI0NDZhN2U1MDlhNDQ2ZjVmZWEwMDg2ZDNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w8P3Sy0YOvihLqsxBl7Va9cInYDksnOz2e6Xjk8Av6o)
> 
> ![image](https://private-user-images.githubusercontent.com/133557155/335192408-c22317d7-e1c6-45cc-a797-b6163f3822df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxODcwOTMsIm5iZiI6MTcxNzE4Njc5MywicGF0aCI6Ii8xMzM1NTcxNTUvMzM1MTkyNDA4LWMyMjMxN2Q3LWUxYzYtNDVjYy1hNzk3LWI2MTYzZjM4MjJkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQyMDE5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjlkMDljMjRlYjk1ZTYzMzViNDI5ZmRlYmNiYzdlZjQxZDg0YjU2MWFkYzBmZDIwZTVjNDQyNWY4YTI4MjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NIduBBq76Y_I_XXfQLnNtI1qmtfIkBckE4g5eKZKcuk)

That looks much better!~ Working with a larger canvas will make it easier to fine tune each panel.

**Comment by LindezaBlue** [comment]
> yes i agree, move all buttons to the sides, no buttons under comic page and above it to not waste space



> yes i agree, move all buttons to the sides, no buttons under comic page and above it to not waste space

Or, we could have the buttons at the top of the page like most paint programs. This would make the undo/redo buttons more accessible, and that would free up room below to expand the vertical canvas for the workspace.

**Comment by new-sankaku** [comment]
Added a hidden mode for controls and layers. You can turn them on or off by checking the checkbox or using Ctrl+K or Ctrl+L.
We also extended the area below the Canvas. Please check it out. Any feedback is welcome. Thanks!

![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/133557155/b3a05009-e174-4b84-9348-5ff09d038441)

**Comment by LindezaBlue** [comment]
> Added a hidden mode for controls and layers. You can turn them on or off by checking the checkbox or using Ctrl+K or Ctrl+L. We also extended the area below the Canvas. Please check it out. Any feedback is welcome. Thanks!
> 

I've updated and tested the update, however there is no menu at the top _(Red highlighted area from OP)_ like the picture shown above. Also using **Ctrl+L or K** did not seem to work for me. When pressing either key-bind it highlighted my address bar.

I am running Opera Browser, and have checked all my settings and key-bindings to see if there is a conflict, however I haven't noticed anything that would cause this issue.

The preview image you posted looks amazing, but I am unable to test it.

**Current Version install:**
![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/141217866/0713eed0-28ba-4bcb-9d42-fcdde915f0c1)

**Comment by new-sankaku** [comment]
This function itself uses basic HTML and CSS functions, so it seems to be browser-independent. The source on Git was also updated correctly.

The updated HTML, CSS, and JavaScript may not be reloaded correctly due to the browser cache.

I updated the HTML, CSS, and JavaScript versions on Git to notify the browser to update the cache. Checking again may solve the problem, so I hope this will solve it...

By the way, I installed Opera here and checked it, and it worked without any problems. (Windows + Opera)

**Comment by LindezaBlue** [comment]
> This function itself uses basic HTML and CSS functions, so it seems to be browser-independent. The source on Git was also updated correctly.
> 
> The updated HTML, CSS, and JavaScript may not be reloaded correctly due to the browser cache.
> 
> I updated the HTML, CSS, and JavaScript versions on Git to notify the browser to update the cache. Checking again may solve the problem, so I hope this will solve it...
> 
> By the way, I installed Opera here and checked it, and it worked without any problems. (Windows + Opera)

The update worked well, and everything looks very clean and professional!~

The issue I mentioned at the start, is that when working with the vertical format there is a lot of negative space. I was thinking that the size of the workspace for the panels could be increased when working on that type of manga panel orientation. That way there is less negative space and a larger work area.

Since you are using a flex _(I checked the code in inspection mode)_ I took the chance to write some CSS edits and mind you I haven't done CSS in years, but I think think this might help. 

![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/141217866/045abece-eb25-4ba2-9376-2f5009bb30be)

- The canvas-container div is now set to display: flex; justify-content: center; align-items: center; height: 100vh; to center its content both horizontally and vertically within the viewport.

- The inner canvas-container div has a width of 80% of its parent container's width with a maximum width of 1200px to ensure it does not exceed a certain size.

- The canvas elements (mangaImageCanvas and upper-canvas) now have a width and height of 100% of their parent container, allowing them to fill the available space within the canvas-container.

Please take the suggestions with a grain of salt as I am rusty as heck and I am sure my code is wrong, nor can I test the code myself. This was just observations from viewing code from the browsers inspection mode.

Anyways, I really appreciate your work, and thank you for being patient with me, also for taking the time to hear me out.

**Comment by new-sankaku** [comment]
I added a zoom in and zoom out button to the top of the canvas. I think this will allow you to enlarge the canvas. Could you please take a look at how it works? Thank you!

![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/133557155/26773200-57e2-4b0d-8f26-41d699555f70)
![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/133557155/af07bf94-5e8e-482e-8813-eacca691c17d)

**Comment by LindezaBlue** [comment]
> I added a zoom in and zoom out button to the top of the canvas. I think this will allow you to enlarge the canvas. Could you please take a look at how it works? Thank you!

**Tested on latest update:**
![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/141217866/c8cd84ac-8235-4514-9b8c-f42849640f89)

I can report that there is no zoom buttons on the top bar above the window.

**What I have:**
![image](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/141217866/f233ccb3-4391-4ccb-9a75-7b53e270d864)

The zoom feature sounds really exciting, and looks to be like the solution to the idea I mentioned at the start!~ I am really excited to test this out and offer feedback once I can access it. 

Thank you so much for taking the time to try and implement a new feature like this. I hope it helps others as well.

**Comment by new-sankaku** [comment]
Why is that...?😢
I wonder if there's something to the cache update...
I'll take a look when I get home from work.

By the way, if you're checking on the WebUI, please restart the WebUI.

If you just want to check, you should be able to go to the following site.
https://new-sankaku.github.io/SP-MangaEditer/

Have a nice day!

**Comment by LindezaBlue** [comment]
> Why is that...?😢 I wonder if there's something to the cache update... I'll take a look when I get home from work.
> 
> By the way, if you're checking on the WebUI, please restart the WebUI.
> 
> If you just want to check, you should be able to go to the following site. https://new-sankaku.github.io/SP-MangaEditer/
> 
> Have a nice day!

Yes I have been checking with the WebUI exclusively for my testing. I figured it would be best to not include the site you provided so as to avoid confusion when addressing the issues that I am experiencing. 

For my tests I have fully closed out the WebUI completely _(the terminal)_ and have restarted after each update. The issue still persists even when clearing the browser's cache and cookies. For laughs I even did a restart from within the WebUI after updating, and after closing the terminal with a forced restart. No fix from either.

I hope you have a great day as well!~

**Comment by LindezaBlue** [comment]
> Hmm, I'm not sure what the problem is...
> 
> My friend ChatGPT suggested that it might be the browser cache after all.
> 
> I previously solved the problem by updating the version while praying, so I prayed while updating the version this time as well.
> 
> Amen.

Haleluja! Your prayers must have been answered as I was able to do an update and it shows up now. 

It worked really well, and I really like the 1x return button to get back to default zoom, you have really put some great thought into the feature. I think this is a really great addition. 

Thank you so much for adding it.

**Comment by new-sankaku** [comment]
Yay, I'm glad it worked!
It was a bit hectic but I'll try to update the version from now on!
Thank you, please let me know if you have any other ideas!
I'll work on it little by little!
