### ISSUE TITLE
No icon loads in Firefox

### ISSUE THREAD

**Issue by tank-sman** [new-sankaku/stable-diffusion-webui-simple-manga-maker#33]
Hello

I installed this as extension in SD.webui just now, and I find out there is no icon loads in Firefox, as you can see in image (Firefox 127.0.2)
![Firefox screenshot](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/65546026/d2009ffe-d9aa-467a-b7f3-0b182b6517e5)
in chrome 
![Chrome screenshot](https://github.com/new-sankaku/stable-diffusion-webui-simple-manga-maker/assets/65546026/8c43f30b-6c2d-478b-914c-e58b1dbca5d8)

I checked the site and downloaded the gate file separately
The problem is only in Firefox

**Comment by new-sankaku** [comment]
Thanks! I'll check it out!
