### ISSUE TITLE
How to help with UI translation?

### ISSUE THREAD

**Issue by natowi** [new-sankaku/stable-diffusion-webui-simple-manga-maker#41]
Hi, I´d be happy to contribute UI translation for German. 
It looks like you do not have one file with all translatable strings.
Could you point me to the right places where content needs to be translated?

**Comment by new-sankaku** [comment]
Hello! Thank you!
The translation text file is here.
　SP-MangaEditer\js\ui\i18next.js

There is a section like this quite far down, and this is the German translation.

"de": {
"translation": {

I've just put in the machine-translated German translation, so if you get the latest version, it should be there. You can also check it at the following URL:
https://new-sankaku.github.io/SP-MangaEditer/

Thank you for your support!

**Comment by natowi** [comment]
@new-sankaku Great, thank you, I will proofread it :)

**Comment by natowi** [comment]
Looks good so far, just some minor things I need to precise.

"以下のメッセージをどこかに投稿してください…。ありがとう…ゴメンネ。","
-> Am I assuming right, that ゴメンネ is meant here as a phrase of politeness?

**Comment by new-sankaku** [comment]
>The auto translation is a literal translation, but I don´t see a reason, why you would need to apologize.

It's a cultural characteristic of the Japanese. It's difficult to explain, but the apology in this case includes the meaning of thanking the person for doing something for you.
It's true that this may sound strange to people who speak multiple languages, so I've deleted it.

>In the left hand side menu, instead of string "newText" it should say "Horizontal Text" and "Vertical Text" for better usability.
I see… I’ll fix that!
